#!/bin/sh

sxhkd &
~/.config/bin/polylaunch.sh &

##CONFIG
for monitor in $(bspc query -M); do
    bspc monitor "$monitor" -d α β γ δ ε
done

bspc config border_width         3
bspc config window_gap          8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true


bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a steam desktop='^5' state=floating
bspc rule -a Wine desktop='^5' state=floating
bspc rule -a firefox desktop='^2'
bspc rule -a virtualbox desktop='^5' state=floating
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
