#!/bin/sh
# requires: id3v2 python-eyed3
find $HOME/music -type f | while read SONG; do
	DIR=$(dirname "$SONG")
	ARTIST=$(basename "$DIR")
	TITLE=$(basename "$SONG" .mp3)
	echo "$DIR | $ARTIST | $TITLE"
	eyeD3 --remove-all-images "$SONG"
	id3v2 --delete-all "$SONG"
	id3v2 --artist "$ARTIST" --song "$TITLE" -2 "$SONG"
done